# Generated by Django 4.2.7 on 2023-11-19 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='почта'),
        ),
        migrations.AddField(
            model_name='payments',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='имя пользователя'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.CreateModel(
            name='PaymentsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_payments', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='начало платежей')),
                ('stop_payments', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='конец платежей')),
                ('payments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.payments', verbose_name='платежи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'история',
                'verbose_name_plural': 'истории',
            },
        ),
    ]
