# Generated by Django 4.2.7 on 2023-11-20 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_remove_lesson_description_lesson_duration_and_more'),
        ('users', '0006_payments_email_payments_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='курс'),
        ),
    ]
