# Generated by Django 4.2.7 on 2023-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_coursesubscription_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EURO')], default='usd', verbose_name='валюта'),
        ),
    ]
