# Generated by Django 4.2.7 on 2023-11-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons_count',
            field=models.IntegerField(null=True, verbose_name='количество уроков'),
        ),
    ]
