# Generated by Django 4.2.7 on 2023-11-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_course_lessons_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
