# Generated by Django 4.2.7 on 2023-11-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_delete_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(null=True, upload_to='course_preview/', verbose_name='предварительный просмотр курса'),
        ),
    ]
