# Generated by Django 4.2.7 on 2023-11-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_course_lessons_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='продолжительность урока'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество уроков'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='education.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='preview_lesson/', verbose_name='предварительный просмотр урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=150, verbose_name='название урока'),
        ),
    ]
