# Generated by Django 4.2.7 on 2023-11-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_remove_lesson_description_lesson_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons_count',
        ),
    ]
