# Generated by Django 4.2.7 on 2023-12-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_course_author_course_price_course_update_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена курса'),
        ),
    ]
